---
kind: pipeline
type: docker
name: default

environment:
  - HE_USERNAME:
      from_secret: HE_USERNAME
  - HE_PASSWORD:
      from_secret: HE_PASSWORD
  - HE_TOTPKEY:
      from_secret: HE_TOTPKEY
  - CF_APITOKEN:
      from_secret: CF_APITOKEN
  - CF_ACCOUNTID:
      from_secret: CF_ACCOUNTID

steps:
- name: Validate configuration and check changes
  image: stackexchange/dnscontrol
  commands:
    - dnscontrol preview

- name: Push new configuration to providers
  image: stackexchange/dnscontrol
  commands:
    - dnscontrol push