---
kind: pipeline
type: docker
name: default

image_pull_secrets:
- IMAGE_PULL_SECRET

steps:
- name: Push new configuration to providers
  image: registry.kmlabz.com/stargate-cluster/dnscontrol-docker
  pull: always
  environment:
    CF_APITOKEN:
      from_secret: CF_APITOKEN
    CF_ACCOUNTID:
      from_secret: CF_ACCOUNTID
  commands:
    - dnscontrol push